---
- name: Create mailto entry
  cronvar:
    name: MAILTO
    value: "{{ aws_instance_metrics_cronjob_mailto }}"
  when: aws_instance_metrics_cronjob_mailto | default('', true) | trim != ''

- name: Create cronjob
  cron:
    name: "Push CloudWatch metrics"
    minute: "*/5"
    job: "{{ aws_instance_metrics_script_path }}/aws-scripts-mon/mon-put-instance-data.pl --mem-used-incl-cache-buff --mem-util --disk-space-util --disk-path=/ --from-cron"
