---
- name: Download and unarchive scripts release
  unarchive:
    src: https://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.2.zip
    dest: "{{ aws_instance_metrics_script_path }}"
    remote_src: yes

- name: Ensure correct file rights on perl script
  file:
    path: "{{ aws_instance_metrics_script_path }}/aws-scripts-mon/mon-put-instance-data.pl"
    state: file
    mode: 0770
